### ISSUE TITLE
Litex python coding issue

### ISSUE THREAD

**Issue by sebo83910** [sebo83910/litex_axi_converter#10]
@enjoy-digital 
This is a question for Florent.

cf. line 160 of axi_converter.py file.
#SEBO: How to retrieve from LiteX the clock, reset and interface names?

**Comment by enjoy-digital** [comment]
@sebo83910: In this example, the clk/rst names are directly obtained from the platform IOs, so they will be the one defined here: https://github.com/sebo83910/litex_axi_converter/blob/main/axi_converter.py#L85-L88.

**Comment by sebo83910** [comment]
Ok I get it but is there a way (function) to retrieve them instead of hardcoding them like this?
tcl.append("proc_add_bus_clock \"{}\" \"{}\" \"{}\"".format("**axis_clk", "axis_in:axis_out", "axis_rst**"))

**Comment by sebo83910** [comment]
This will not be fixed.
